version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    ports:
      - "3000:3000"
    depends_on: 
      - server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.server
    env_file: ./server/.env
    ports:
      - "5000:5000"
    depends_on: 
      - local-mongo
  local-mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
volumes:
  mongodb-data: